---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: bootstrap-kali
    image: kalilinux/kali-linux-docker
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
    options:
      exclude:
        - meta/version.yml
        - meta/exception.yml
  inventory:
    host_vars:
      bootstrap-kali:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: kali
