---
sudo: required
language: python
services: docker

env:
  - ANSIBLE_VERSION: "ansible>=2.0.0.0,<2.1.0.0"
  - ANSIBLE_VERSION: "ansible>=2.1.0.0,<2.2.0.0"
  - ANSIBLE_VERSION: "ansible>=2.2.0.0,<2.3.0.0"
  - ANSIBLE_VERSION: "ansible>=2.3.0.0,<2.4.0.0"
  - ANSIBLE_VERSION: "ansible>=2.4.0.0"

cache:
 - pip

install:
- pip install "$ANSIBLE_VERSION"
- pip install molecule
- pip install docker-py

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
