---
sudo: required
language: python
services: docker

env:
  - distro: centos:7
  - distro: centos:6
  - distro: fedora:25
  - distro: fedora:26
  - distro: debian:7
  - distro: debian:8
  - distro: debian:9
  - distro: ubuntu:14.04
  - distro: ubuntu:16.04
  - distro: ubuntu:17.10
  - distro: alpine:3.1
  - distro: alpine:3.2
  - distro: alpine:3.3
  - distro: alpine:3.4
  - distro: alpine:3.5
  - distro: alpine:3.6

before_install:
  - docker pull "${distro}"

install:
  - pwd
  - ls
  - find
  - containerid=$(docker container run --detach --volume $(pwd):/etc/ansible/roles/testing ${distro} sleep 300)
  - if [[ distro == centos:* ]] ; then docker exec ${containerid} yum -y install ansible ; fi
  - if [[ distro == fedora:* ]] ; then docker exec ${containerid} dnf -y install ansible ; fi
  - if [[ distro == debian:* ]] ; then docker exec ${containerid} "bash -c 'apt-get update ; apt-get install ansible'" ; fi
  - if [[ distro == ubuntu:* ]] ; then docker exec ${containerid} "bash -c 'apt-get update ; apt-get install ansible'" ; fi
  - if [[ distro == alpine:* ]] ; then docker exec ${containerid} apk add --no-cache ansible ; fi
  - docker exec ${containerid} pwd
  - docker exec ${containerid} ls
  - docker exec ${containerid} find

script:
  - docker exec ${containerid} ansible-playbook /etc/ansible/roles/tests/test.yml --syntax-check
  - docker exec ${containerid} ansible-playbook /etc/ansible/roles/tests/test.yml --connection=local --sudo

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
