---
sudo: required
language: python
services: docker

env:
  - distro: centos/7
  - distro: centos/6
  - distro: fedora/25
  - distro: fedora/26

before_install:
- docker pull "${distro}"

install:
  - containerid=$(docker run --volume $(pwd):/etc/ansible/roles/testing ${distro} --quiet)
  - docker exec ${containerid} yum -y install ansible

script:
  - docker exec ${containerid} ansible-playbook /etc/ansible/roles/tests/test.yml --syntax-check
  - docker exec ${containerod} ansible-playbook /etc/ansible/roles/tests/test.yml --connection=local --sudo

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
