---
sudo: required
language: python
services: docker

cache:
 - pip

install:
- pip install ansible
- pip install molecule

script:
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
