---
# tasks file for bootstrap
- name: register release
  raw: cat /etc/*-release
  register: release
  changed_when: false
  become: no

- name: install software on alpine
  raw: apk update ; apk add python sudo
  when:
    - "'alpine' in release.stdout"
  register: alpine
  changed_when:
    - "'Installing python' in alpine.stdout"
  remote_user: "{{ bootstrap_user }}"

- name: install software on centos
  raw: yum -y install python2 sudo
  when:
    - "'CentOS' in release.stdout"
  register: centos
  changed_when:
    - "'Nothing' not in centos.stdout"
  remote_user: "{{ bootstrap_user }}"

- name: install software debian
  raw: apt-get update ; apt-get -y install python sudo
  when:
    - "'Debian' in release.stdout"
  register: debian
  changed_when:
    - "' 0 newly installed' not in debian.stdout"
  remote_user: "{{ bootstrap_user }}"

- name: install software on fedora
  raw: yum -y install python2 python2-dnf sudo
  when:
    - "'Fedora' in release.stdout"
  register: fedora
  changed_when:
    - "'Nothing' not in fedora.stdout"
  remote_user: "{{ bootstrap_user }}"

- name: install software opensuse
  raw: zypper -n install python python-xml sudo
  when:
    - "'openSUSE' in release.stdout"
  register: opensuse
  changed_when:
    - "'Nothing' not in opensuse.stdout"
  remote_user: "{{ bootstrap_user }}"
  failed_when: no

- name: install software ubuntu
  raw: apt-get update ; apt-get -y install python sudo
  when:
    - "'Ubuntu' in release.stdout"
  register: ubuntu
  changed_when:
    - "' 0 newly installed' not in ubuntu.stdout"
  remote_user: "{{ bootstrap_user }}"

- name: gather facts
  setup:
  become: no

- name: install extra software
  package:
    name: "{{ item }}"
  with_items:
    - "{{ bootstrap_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(bootstrap_packages[ansible_distribution]
      | default(bootstrap_packages['default'] )) }}"
