---
- name: install python2
  raw: sh -c "test -e /usr/bin/python || (yum -y install python2)"
  register: python2install
  changed_when: "python2install.stdout != ''"

- name: gather facts
  setup:
    
- name: install python2-dnf
  package:
    name: python2-dnf
    state: present
  when:
    - ansible_distribution == "Fedora"

- name: install libselinux-python and python-simplejson
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - python-simplejson
  when:
    - ( ansible_distribution == "Fedora" or ( ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" )
   
