---
- name: test release
  raw: cat /etc/*-release
  register: release
  changed_when: false

- name: install python on alpine
  raw: apk update ; apk add python
  when: "'alpine' in release.stdout"

- name: install python on ubuntu or debian
  raw: apt-get update ; apt-get install python
  when: ( "'Ubuntu' in release.stdout" or "'Debian' in release.stdout" )

- name: install python on fedora, centos or red hat
  raw: yum -y install python2
  when: ( "'Fedora' in release.stdout" or "'CentOS' in release.stdout" or "'Red Hat' in release.stdout" )

- name: install python2
  raw: sh -c "test -e /usr/bin/python || (yum -y install python2)"
  register: python2install
  changed_when: "python2install.stdout != ''"

- name: gather facts
  setup:

- name: install python2-dnf
  package:
    name: python2-dnf
    state: present
  when:
    - ansible_distribution == "Fedora"

- name: install libselinux-python and python-simplejson
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - python-simplejson
  when:
    - ( ansible_distribution == "Fedora" or ( ansible_distribution == "CentOS" and ansible_distribution_major_version == "6" ) )
