---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: bootstrap-rhel-latest
    image: ubi8/ubi
    pre_build_image: yes
    registry:
      url: registry.access.redhat.com
      credentials:
        username: ${registry_redhat_io_username}
        password: ${registry_redhat_io_password}
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: redhat-latest
