---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: bootstrap-ubuntu-latest
    image: ubuntu:latest
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
    options:
      exclude:
        - meta/version.yml
        - meta/exception.yml
  inventory:
    host_vars:
      bootstrap-ubuntu-latest:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: ubuntu-latest
