---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
  safe_files: []
  options:
    managed: yes
    ansible_connection_options:
      connection: ssh
      ansible_ssh_common_args: -F $MOLECULE_EPHEMERAL_DIRECTORY/ssh-config
lint:
  name: yamllint
platforms:
  - name: bootstrap-fedora
    image_id: fedora-28-x64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: digitalocean
verifier:
  name: goss
  lint:
    name: yamllint
